### ISSUE TITLE
Distribute via Flathub

### ISSUE THREAD

**Issue by gary-host-laptop** [Darazaki/Spedread#1]
Awesome application you have here, I've been looking for something like this for some time and the fact that it uses GTK it's just even more awesome. Having a more user friendly distribution format would be great and being on Flathub will also help to get the application to be more known and possibly someone will help you with development.

**Comment by gary-host-laptop** [comment]
If you have any doubts on how to package it as a flatpak you can join #flatpak:matrix.org and ask the developers for helpl.

**Comment by Darazaki** [comment]
Good idea! I'm currently rewriting the app in Vala & GTK4 inside the `v2` branch. I've pretty much finished the coding part so I only need to copy and reorganize the application files so the app should get published soon!

I'll keep you updated

Also, thanks a lot for the Matrix room! That'll probably be very helpful :D

**Comment by gary-host-laptop** [comment]
Are you planning on publishing this on elementaryOS? Since they use Vala for all their applications and Flatpak for their package manager (on a different repo, not on Flathub).

**Comment by Darazaki** [comment]
Sadly it looks like [they only allow GTK3](https://github.com/elementary/houston/wiki/Before-You-Publish#native-front-end) :/

But maybe I'm wrong so I'll have to see

**Comment by gary-host-laptop** [comment]
Yep, you're right, worth noting that they are working on adding support for GTK4 in elementaryOS 7.0, which should be released around Q2 of 2022. https://github.com/elementary/stylesheet/pull/1108

Still it's up to you if you want it to be released there as a curated application, since elementary users will still be able to install it through Flathub.

**Comment by Darazaki** [comment]
Oh ok thanks for telling me! I don't really follow their development cycle so that's pretty useful to know :)

Just in case I ended up asking the question [their StackExchange](https://elementaryos.stackexchange.com/q/29383/27700) but I guess that'll be the answer

Also, the only thing missing for me to publish Spedread on Flathub is fixing a weird bug where IBus input methods don't seem to work with the Flatpak build and *maybe* translating the app's description into French so hopefully I'll be able to submit Spedread there in the next few days! :D

**Comment by gary-host-laptop** [comment]
> Oh ok thanks for telling me! I don't really follow their development cycle so that's pretty useful to know :)
> 
> Just in case I ended up asking the question [their StackExchange](https://elementaryos.stackexchange.com/q/29383/27700) but I guess that'll be the answer

They will probably give you a more technical answer with more details, so it doesn't hurt.

> Also, the only thing missing for me to publish Spedread on Flathub is fixing a weird bug where IBus input methods don't seem to work with the Flatpak build and _maybe_ translating the app's description into French so hopefully I'll be able to submit Spedread there in the next few days! :D

Hope you can fix that bug, regarding the French translation, you could use DeepL which is an amazing translator and will probably do the trick.

Translation to French:

>Logiciel de lecture rapide GTK : Lisez comme un speedrunner ! 
>
>### Spedread
>
>Logiciel de lecture rapide GTK : Lisez comme un speedrunner !
>
>Ce programme affiche rapidement un mot à la fois pour permettre de se concentrer sur l'idée générale plutôt que sur des mots isolés, tout en réduisant les mouvements oculaires.
>
>Caractéristiques
>
>capture d'écran
>
> * International
> * Lecture, pause, mot suivant et mot précédent
> * Contrôle de la vitesse à laquelle les mots sont affichés

**Comment by Darazaki** [comment]
That translation looks pretty nice! Just needs a few tweaks. Using DeepL is actually a really good idea thanks! :)

**Comment by Darazaki** [comment]
https://flathub.org/apps/details/com.github.Darazaki.Spedread :D

**Comment by gary-host-laptop** [comment]
Awesome!

**Comment by Darazaki** [comment]
Oh and btw, the IBus method bug seems to just be an issue with my build tools. No issue if you download from Flathub so... fixed I guess?

Anyway thanks a lot for your suggestions and have a nice day! :)
