### ISSUE TITLE
Show time remaining

### ISSUE THREAD

**Issue by ghost** [Darazaki/Spedread#12]
Maybe somewhere near the resume button, it would be nice to show how much longer the reading will take at the set pace and the time at which it'll be done.

**Comment by Darazaki** [comment]
Sorry for the wait and yeah, that's a good idea! I think I'll make it visible only when the reading is paused/stopped that way it shouldn't be too distracting

Something like:

![image](https://github.com/Darazaki/Spedread/assets/36732679/02d03771-735b-4730-807f-5f85c43722d5)

Except that the text would be in the default font and right above the "play" button (or maybe inside it? will need to experiment)

**Comment by Darazaki** [comment]
Hi! I've implemented this feature in v2.4.0 which I've just released :)

v2.4.0 is available on the AUR and should be available on Flathub in ~4h

Thanks for your suggestion!
