### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by pafri** [Darazaki/Spedread#17]
Hi,

I send thre Czech localization file to be included into the program. Zipped. Attached.

Greetings
[Spedread_cs.zip](https://github.com/Darazaki/Spedread/files/11332077/Spedread_cs.zip)

**Comment by Darazaki** [comment]
Hi and sorry for the wait. Your .po file looks perfect to me, I'll publish your localization in the next update

Thanks :)

**Comment by pafri** [comment]
Fine. No rush. :-)
