### ISSUE TITLE
Started Building and Maintaining Snap Packages

### ISSUE THREAD

**Issue by ghost** [Darazaki/Spedread#19]
@Darazaki  I have started building and maintaining snap packages for this app.

Source/Manifest: https://github.com/CapeCrusader321/Spedread-Snap

<a href="https://snapcraft.io/spedread">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

**Comment by Darazaki** [comment]
Hi and thanks a lot! I don't know much about snap but judging from the `-Dadw_1_2=true` it looks like you know what you're doing ;)

If you need anything to make maintaining this package easier (like me adding a config file to this repoitory or notifying you before I publish an update) feel free to ask!
