### ISSUE TITLE
Snap package queries

### ISSUE THREAD

**Issue by sameersharma2006** [Darazaki/Spedread#27]
Hey there, snap maintainer here, will you like to take up the ownership of snap package under your hood ?
I can work as collaborator to help you maintain the snap.
It will be good if the snap package is distributed  by you.

Regards.

**Comment by Darazaki** [comment]
Sure and thank you for your work!

Honestly, I have no idea how maintaining a snap works so here are some questions for you:

- What would I need to do to update it?
- Are there runtimes that also need to be updated regularly? (e.g. GNOME Platform on Flatpak)
- Do I need to have an account on Snapcraft / Launchpad / etc?

**Comment by sameersharma2006** [comment]
> Sure and thank you for your work!
🙏
 
>   What would I need to do to update it?

You will need an account for snapcraft and then you can manage your snaps at https://snapcraft.io/snaps
For updating you edit the Snap YAML file, request a new snap to be built from the edited YAML and then test the snap on the edge channel and once satisfied push it to stable by choosing your snap at  https://snapcraft.io/snaps and then going to releases.

![image](https://github.com/Darazaki/Spedread/assets/164338475/c342a642-ab96-40c2-8df6-8ed87ac97ceb)

![image](https://github.com/Darazaki/Spedread/assets/164338475/ab2ab629-efb6-4d10-8d93-6c7749f7dc57)

![image](https://github.com/Darazaki/Spedread/assets/164338475/543609ef-2594-4c65-9919-d307a6b99ab5)

![image](https://github.com/Darazaki/Spedread/assets/164338475/95b1b084-9420-443f-9242-ef7baba6c525)


>  Are there runtimes that also need to be updated regularly? (e.g. GNOME Platform on Flatpak)

Yes but unlike flatpak, snap gnome SDKs are based on Ubuntu LTS releases and are supported for 5 years , each Ubuntu LTS has a corresponding snap core(Like Ubuntu 22.04-> core22), and each core has its own gnome SDK(core22-> gnome-42-2204) so if you want stability you can update SDKs after every five year or along with new release of ubuntu every 2 years. {Ubuntu 24.04 -> core24 -> gnome-46-2404 (Upcoming) }.

>   Do I need to have an account on Snapcraft / Launchpad / etc?

Yes Snapcraft Account is a must but launchpad is optional and won't be needed.

**Comment by sameersharma2006** [comment]
@Darazaki  For more info see https://snapcraft.io/docs/create-a-new-snap

**Comment by sameersharma2006** [comment]
@Darazaki  See https://snapcraft.io/docs/gtk4-applications for more details

**Comment by Darazaki** [comment]
Thank you for your explanation, that's very helpful!

I've made a Snapcraft account with the username `darazaki`, please tell me if you need anything else to give me the snap's ownership. I'll edit Spedread's README afterward :)

**Comment by sameersharma2006** [comment]
@Darazaki  Ok, since Saturday & Sunday are holidays for canonical employees, i will open a snap ownership transfer request in snapcraft forum on Monday.

**Comment by sameersharma2006** [comment]
@Darazaki  I have opened the request viz. https://forum.snapcraft.io/t/transfer-snap-to-upstream/39868

If possible just chip in the forum post and give your nod/consent to the transfer

**Comment by sameersharma2006** [comment]
@Darazaki  Can i have your email to add you as collaborator its needed to complete the transfer.

**Comment by Darazaki** [comment]
My email is: `n [dot] darazaki [at] gmail [dot] com`

I'll post a reply in the forum once I'll have accepted your invite

**Comment by sameersharma2006** [comment]
> My email is: `n [dot] darazaki [at] gmail [dot] com`
> 
> I'll post a reply in the forum once I'll have accepted your invite

Ok, Done.

**Comment by Darazaki** [comment]
I've finally updated the README so I'm gonna close this issue now. I'll take some time to see exactly how snaps work this weekend

Thanks again for your work and goodbye! :)
