### ISSUE TITLE
Add PKGBUILD

### ISSUE THREAD

**Issue by asakura42** [Darazaki/Spedread#7]
Hello. Could you add PKGBUILD file for Arch User Repository if you're familiar with it?

**Comment by Darazaki** [comment]
Hi! Looks like [somebody has just finished adding Spedread to the AUR](https://aur.archlinux.org/packages?O=0&K=spedread). Since the PKGBUILD looks perfect I'll close this issue :)

igor-dyatlov if you're seeing this, thanks a lot! :D
