### ISSUE TITLE
Tabs?

### ISSUE THREAD

**Issue by deadpahn** [Darazaki/Spedread#9]
Hi,

Love this program. Was wondering if you could add TABS to it? I'm currently reading a book at the moment but need to context switch to something else I would like to read. Problem is, there is no PDF support or something like that, so Im in the middle of a massive COPY PAST I did to go around the limitation. Having to figure out where I was in a 300 page book just to read an article or something that goes with the text but not in the book is kind of a drag.

Thanks!

**Comment by Darazaki** [comment]
Yeah, that's definitely a pain. I've actually explicitly set `ApplicationFlags.NON_UNIQUE` so you can start several instances of the app (depending on your DE, you can start a new instance by right clicking the app icon and then selecting "New Window" or something similar)

Though the fact that you haven't found it means I've done a bad job at UX/making it obvious. If you're fine with that I'll add a "New Window" button in the main menu hopefully this week and then close this issue :)

Thanks for reporting this issue and I'm glad you like my app <3

**Comment by Darazaki** [comment]
After much more time than expected, I've finally implemented the "new window" button! :D

I've also added a "quick paste" button to make it easier to read lots of short texts

These additions should be available on Flathub soon and hopefully the AUR too, feel free to tell me what your think about them :)

**Comment by deadpahn** [comment]
Wow! That's great! Thank you.
